# Generated by Django 4.2.5 on 2023-09-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plyta',
            name='wykonawca',
        ),
        migrations.AlterField(
            model_name='plyta',
            name='nosnik',
            field=models.CharField(choices=[('CD', 'CD'), ('Vinyl', 'Vinyl')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plyta',
            name='tytul',
            field=models.CharField(max_length=100),
        ),
    ]
