# Generated by Django 4.2.5 on 2023-09-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_plyta_artysta'),
    ]

    operations = [
        migrations.AddField(
            model_name='plyta',
            name='zdjecie',
            field=models.CharField(default='none', max_length=1000),
            preserve_default=False,
        ),
    ]
